"""把 Wave 2 新增数据集条目合并进 catalog.json（幂等，可重复运行）。

设计要点
- catalog.json 仍是「元数据单一事实来源」。本脚本只做合并：按 id 命中则原地替换
  （便于修订元信息），未命中则追加。重复运行结果一致。
- 条目按 tier 顺序（basic→advanced→deep→expert）稳定排序，便于人工审阅。
- 只改 catalog.json，不碰任何 .jsonl 数据文件。

用法
    /path/to/harness/.venv/bin/python tools/add_catalog_entries.py [--dry-run]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "eval_harness" / "datasets" / "catalog.json"
TIER_ORDER = ["basic", "advanced", "deep", "expert"]


def _curated(entry: dict) -> dict:
    """给「本地构造样本」条目补上统一声明，避免逐条手写遗漏。"""
    entry.setdefault("source_kind", "internal" if entry.get("license") == "内部自研" else "hf_dataset")
    entry["sample_built"] = "2026-09-17"
    return entry


NEW: list[dict] = [
    # ---------------- 基础档 ----------------
    _curated({
        "id": "arc-basic",
        "name": "ARC（科学推理·基础子集）",
        "tier": "basic",
        "category": "通用大模型 / 科学推理",
        "object_axes": ["general_llm"],
        "dimensions": ["scientific_reasoning", "knowledge"],
        "description": "中小学科学常识推理基准（ARC-Challenge），测多步科学推理与因果判断，比纯知识题更贴近「会不会推理」。",
        "source": "Clark et al. 2018 · arXiv:1803.05457 · allenai/ai2_arc",
        "official_url": "https://huggingface.co/datasets/allenai/ai2_arc",
        "aligned_to": "ARC-Challenge",
        "license": "CC-BY-SA-4.0",
        "commercial_use": True,
        "version": "v1.0 (数据集本身 2018)",
        "updated": "2018-03",
        "data_format": "JSONL (harness Case, MCQ)",
        "recommended_grader": "code(exact/contains)",
        "suite_file": "arc_basic.jsonl",
        "cases_count": 10,
        "full_scale": "约 7,787 题（其中 Challenge 1,172 题）",
        "est_duration_min": 2,
        "est_tokens": 4000,
        "languages": ["en"],
        "scenario": "科学推理入门位：交付验收里「这个模型会不会做题之外的思考」的轻量判据，可商用。",
        "access": "已随仓库预置可跑样本；官方抽样需联网主机执行 tools/fetch_datasets.py --only arc-basic --force。",
        "sample_note": "本地构造 10 题代表性样本（结构对齐 ARC 四选一，覆盖物理/化学/生物/天文/地球科学），非官方原始数据；联网主机可替换为官方抽样。",
        "recommends_judge": False,
    }),
    _curated({
        "id": "cmmlu-basic",
        "name": "CMMLU（中文综合·基础子集）",
        "tier": "basic",
        "category": "通用大模型 / 单轮问答·知识（中文·中国特定知识）",
        "object_axes": ["general_llm"],
        "dimensions": ["single_turn_qa", "knowledge", "china_specific"],
        "description": "中文综合能力基准，含大量中国特有的历史、地理、法律与文化知识——外文模型最易翻车的部分。",
        "source": "Li et al. 2023 · arXiv:2306.09212 · hails/CMMLU",
        "official_url": "https://huggingface.co/datasets/hails/CMMLU",
        "aligned_to": "CMMLU",
        "license": "见官方仓库（商用前需确认）",
        "commercial_use": False,
        "version": "v1.0 (数据集本身 2023)",
        "updated": "2023-06",
        "data_format": "JSONL (harness Case, MCQ)",
        "recommended_grader": "code(exact/contains)",
        "suite_file": "cmmlu_basic.jsonl",
        "cases_count": 10,
        "full_scale": "约 11,000 题 / 67 学科",
        "est_duration_min": 2,
        "est_tokens": 4000,
        "languages": ["zh"],
        "scenario": "面向中国客户的必测项：中文语境下的「中国特定知识」正确性，与 C-Eval 互补。",
        "access": "已随仓库预置可跑样本；官方抽样需联网主机执行 fetch。许可待确认，商用前须法务确认。",
        "sample_note": "本地构造 10 题代表性样本（宪法/民法/婚龄/地理/历史/传统文化等中国特定知识四选一），非官方原始数据。",
        "recommends_judge": False,
    }),
    _curated({
        "id": "agieval-basic",
        "name": "AGIEval（中国标准化考试·基础子集）",
        "tier": "basic",
        "category": "通用大模型 / 应试能力（中国标准化考试）",
        "object_axes": ["general_llm"],
        "dimensions": ["single_turn_qa", "reasoning", "china_specific"],
        "description": "以中国高考、公务员考试、法考等真实标准化试题为底的能力基准，考察「人类考试语境」下的推理与知识运用。",
        "source": "Zhong et al. 2023 · arXiv:2304.06364 · microsoft/AGIEval",
        "official_url": "https://github.com/microsoft/AGIEval",
        "aligned_to": "AGIEval",
        "license": "MIT",
        "commercial_use": True,
        "version": "v1.0 (数据集本身 2023)",
        "updated": "2023-04",
        "data_format": "JSONL (harness Case, MCQ)",
        "recommended_grader": "code(exact/contains)",
        "suite_file": "agieval_basic.jsonl",
        "cases_count": 10,
        "full_scale": "约 8,000+ 题（多考试体系）",
        "est_duration_min": 2,
        "est_tokens": 4000,
        "languages": ["zh", "en"],
        "scenario": "中国考试语境的应试能力位：政企客户内部模型选型时最容易建立共识的评测口径，可商用。",
        "access": "已随仓库预置可跑样本；官方抽样需联网主机执行 fetch。",
        "sample_note": "本地构造 10 题代表性样本（高考数学/物理/化学/生物/英语、公务员判断推理与常识、法考刑法），非官方原始数据。",
        "recommends_judge": False,
    }),
    _curated({
        "id": "math-basic",
        "name": "MATH（竞赛数学·基础子集）",
        "tier": "basic",
        "category": "通用大模型 / 数学推理",
        "object_axes": ["general_llm"],
        "dimensions": ["math_reasoning", "single_turn_qa"],
        "description": "竞赛级数学题基准，比 GSM8K 难度更高，测严格的多步符号推理与最终答案精确性。",
        "source": "Hendrycks et al. 2021 · arXiv:2103.03874 · hendrycks/competition_math",
        "official_url": "https://huggingface.co/datasets/hendrycks/competition_math",
        "aligned_to": "MATH",
        "license": "MIT",
        "commercial_use": True,
        "version": "v1.0 (数据集本身 2021)",
        "updated": "2021-03",
        "data_format": "JSONL (harness Case, 数值/符号答案)",
        "recommended_grader": "code(contains, 数值核心匹配)",
        "suite_file": "math_basic.jsonl",
        "cases_count": 10,
        "full_scale": "约 12,500 题（含 7 个学科子集）",
        "est_duration_min": 3,
        "est_tokens": 8000,
        "languages": ["en", "zh"],
        "scenario": "数学推理进阶位：与 GSM8K 形成梯度（小学→竞赛），用于区分「会算」与「会推理」，可商用。",
        "access": "已随仓库预置可跑样本；官方抽样需联网主机执行 fetch。",
        "sample_note": "本地构造 10 题代表性样本（数列/代数/概率/立体几何/对数），答案为唯一数值，已逐题核对，非官方原始数据。",
        "recommends_judge": False,
    }),
    # ---------------- 进阶档 ----------------
    _curated({
        "id": "injection-advanced",
        "name": "提示注入抵抗（自研·进阶）",
        "tier": "advanced",
        "category": "智化融合系统 / 集成风险面·提示注入",
        "object_axes": ["integration_risk"],
        "dimensions": ["safety", "prompt_injection", "input_trust"],
        "description": "验收「输入侧不可信」：当网页、检索资料、工具返回或用户输入夹带指令时，Agent 能否坚持原任务而不被劫持。",
        "source": "本项目自研（对齐 OWASP Top 10 for LLM Applications · LLM01 Prompt Injection）",
        "official_url": "https://owasp.org/www-project-top-10-for-large-language-model-applications/",
        "aligned_to": "OWASP LLM01 · Garak",
        "license": "内部自研",
        "commercial_use": True,
        "version": "v1.0",
        "updated": "2026-09",
        "data_format": "JSONL (harness Case, grader=permission)",
        "recommended_grader": "permission",
        "suite_file": "injection_advanced.jsonl",
        "cases_count": 10,
        "full_scale": "可随项目扩展（按注入载体 × 目标动作矩阵）",
        "est_duration_min": 5,
        "est_tokens": 20000,
        "languages": ["zh", "en"],
        "scenario": "交界层核心风险面之一：Agent 接外部内容就会被注入，这是「外壳接口通、内核被带走」最典型的翻车方式。覆盖指令覆盖、间接注入、RAG 投毒、权限提升、编码绕过、语言切换、伪 system 标签、续写攻击、SQL 注入、数据内嵌指令共 10 类载体。",
        "access": "已随仓库预置可跑样本（grader=permission，确定性判分，无需 judge 模型）。",
        "source_kind": "internal",
        "sample_note": "本地构造 10 题，每题标注 injection_type 与对应的 denied_tools；gold 为「识别注入 + 拒绝执行 + 回到原任务」的合规回复。非官方原始数据。",
        "recommends_judge": False,
    }),
    _curated({
        "id": "jailbreak-advanced",
        "name": "越狱抵抗（自研·进阶）",
        "tier": "advanced",
        "category": "智化融合系统 / 安全·越狱与绕过",
        "object_axes": ["safety_agent"],
        "dimensions": ["safety", "jailbreak_resistance"],
        "description": "验收「安全策略能否被话术绕过」：人格覆盖、虚构包装、逐步诱导、权威冒充、学术名义、激将、编码混淆、多轮铺垫、情感操纵、伪造授权。",
        "source": "本项目自研（对齐 HarmBench / JailbreakBench / AdvBench 的攻击手法分类）",
        "official_url": "https://github.com/centerforaisafety/HarmBench",
        "aligned_to": "HarmBench · JailbreakBench · AdvBench",
        "license": "内部自研",
        "commercial_use": True,
        "version": "v1.0",
        "updated": "2026-09",
        "data_format": "JSONL (harness Case, grader=permission)",
        "recommended_grader": "permission",
        "suite_file": "jailbreak_advanced.jsonl",
        "cases_count": 10,
        "full_scale": "可随项目扩展",
        "est_duration_min": 5,
        "est_tokens": 20000,
        "languages": ["zh", "en"],
        "scenario": "与提示注入互补：注入是「被外部内容带偏」，越狱是「被话术说服」。高安要求场景（金融/政企）上线的安全基线。",
        "access": "已随仓库预置可跑样本（grader=permission，确定性判分，无需 judge 模型）。",
        "source_kind": "internal",
        "sample_note": "本地构造 10 题，每题标注 jailbreak_type；请求本身以抽象方式描述，不含任何可操作的有害细节，gold 均为合规拒绝。非官方原始数据。",
        "recommends_judge": False,
    }),
    _curated({
        "id": "safetybench-advanced",
        "name": "SafetyBench（中文安全·进阶子集）",
        "tier": "advanced",
        "category": "智化融合系统 / 安全·内容安全（中文）",
        "object_axes": ["safety_agent"],
        "dimensions": ["safety", "content_safety", "china_compliance"],
        "description": "中文内容安全基准，覆盖冒犯性、偏见歧视、身心健康、非法活动、伦理道德、隐私财产、未成年人保护七类，含医疗/金融越界。",
        "source": "Zhang et al. 2023 · arXiv:2309.07045 · thu-coai/SafetyBench",
        "official_url": "https://huggingface.co/datasets/thu-coai/SafetyBench",
        "aligned_to": "SafetyBench",
        "license": "见官方仓库（商用前需确认）",
        "commercial_use": False,
        "version": "v1.0 (数据集本身 2023)",
        "updated": "2023-09",
        "data_format": "JSONL (harness Case, grader=permission)",
        "recommended_grader": "permission",
        "suite_file": "safetybench_advanced.jsonl",
        "cases_count": 10,
        "full_scale": "约 11,435 题 / 7 大类",
        "est_duration_min": 5,
        "est_tokens": 20000,
        "languages": ["zh"],
        "scenario": "中国合规向的内容安全位：面向公众服务（有舆论属性）的 Agent 必测。含自伤危机场景的转介要求（12356/120）与医疗金融越界拒绝。",
        "access": "已随仓库预置可跑样本（grader=permission，确定性判分）。官方抽样需联网主机执行 fetch；许可待确认。",
        "source_kind": "hf_dataset",
        "sample_note": "本地构造 10 题代表性样本，覆盖 SafetyBench 七类并补充未成年人保护与医疗/金融越界两类实务场景；crisis_referral 字段记录危机转介要求。非官方原始数据。",
        "recommends_judge": False,
    }),
    _curated({
        "id": "pii-advanced",
        "name": "PII 保护与脱敏（自研·进阶）",
        "tier": "advanced",
        "category": "智化融合系统 / 集成风险面·隐私保护",
        "object_axes": ["integration_risk"],
        "dimensions": ["safety", "privacy", "deidentification"],
        "description": "验收「Agent 处理含个人信息的数据时会不会泄露」：工单摘要、日志、纪要外发、简历初筛、病历摘要、训练数据入库、出境传输、对外回复共 8 个真实落地场景。",
        "source": "本项目自研（对齐《个人信息保护法》最小必要原则与去标识化要求）",
        "official_url": "https://www.gov.cn/xinwen/2021-08/20/content_5632486.htm",
        "aligned_to": "个人信息保护法 · 去标识化",
        "license": "内部自研",
        "commercial_use": True,
        "version": "v1.0",
        "updated": "2026-09",
        "data_format": "JSONL (harness Case, grader=sandbox 结构化断言)",
        "recommended_grader": "sandbox",
        "suite_file": "pii_advanced.jsonl",
        "cases_count": 8,
        "full_scale": "可随项目扩展",
        "est_duration_min": 4,
        "est_tokens": 16000,
        "languages": ["zh"],
        "scenario": "B 端最容易被忽略的合规翻车点。判分方式是沙箱内断言：输出中不得出现占位敏感串原文，且必须满足结构化字段要求——比人工抽查可靠。",
        "access": "已随仓库预置可跑样本（grader=sandbox，纯本地判分，无需 judge 模型）。",
        "source_kind": "internal",
        "sample_note": "本地构造 8 题，敏感数据均为虚构占位值（如 13800138000），check_code 断言其不得出现在输出、且输出满足字段契约。非官方原始数据。",
        "recommends_judge": False,
    }),
    _curated({
        "id": "idempotency-advanced",
        "name": "幂等与重试安全（自研·进阶）",
        "tier": "advanced",
        "category": "智化融合系统 / 集成风险面·幂等与并发",
        "object_axes": ["integration_risk"],
        "dimensions": ["safety", "idempotency", "reliability"],
        "description": "验收「重复与并发会不会造成重复扣款/重复副作用」：重复提交、误判重复、超时重试、乐观锁冲突、重复消费、幂等键过期、Saga 部分失败、跨服务重试共 8 类。",
        "source": "本项目自研（业界幂等与分布式事务工程实践）",
        "official_url": "qe-platform 交界层原子评测器扩展",
        "aligned_to": "分布式系统幂等性工程实践",
        "license": "内部自研",
        "commercial_use": True,
        "version": "v1.0",
        "updated": "2026-09",
        "data_format": "JSONL (harness Case, grader=sandbox 结构化断言)",
        "recommended_grader": "sandbox",
        "suite_file": "idempotency_advanced.jsonl",
        "cases_count": 8,
        "full_scale": "可随项目扩展",
        "est_duration_min": 4,
        "est_tokens": 16000,
        "languages": ["zh"],
        "scenario": "确定性软件壳与 Agent 交界处最容易出钱的故障面：Agent 决定「重试还是跳过」时判错，直接造成重复扣款或丢单。判分要求输出结构化 decision 字段后断言，客观可复现。",
        "access": "已随仓库预置可跑样本（grader=sandbox，纯本地判分）。",
        "source_kind": "internal",
        "sample_note": "本地构造 8 题，每题要求输出含 decision/reason_code 的 JSON，check_code 断言决策取值正确（如重复键必须 skip、结果未知必须 reconcile）。非官方原始数据。",
        "recommends_judge": False,
    }),
    _curated({
        "id": "consistency-advanced",
        "name": "跨环境一致性（自研·进阶）",
        "tier": "advanced",
        "category": "智化融合系统 / 差异化空白·跨环境一致性",
        "object_axes": ["integration_risk"],
        "dimensions": ["consistency", "multi_turn", "environment"],
        "description": "验收「同一个 Agent 换个环境/换一轮对话，答案会不会变」：配置口径冲突、跨轮约束保持、单位归一、时区归一、指标口径、版本漂移、跨轮数值自洽、命名口径共 8 类。",
        "source": "本项目自研（本项目点名的四项市场空白之一）",
        "official_url": "qe-platform 交界层原子评测器扩展",
        "aligned_to": "本项目自定义（公开数据集无对应基准）",
        "license": "内部自研",
        "commercial_use": True,
        "version": "v1.0",
        "updated": "2026-09",
        "data_format": "JSONL (harness Case, grader=sandbox 结构化断言)",
        "recommended_grader": "sandbox",
        "suite_file": "consistency_advanced.jsonl",
        "cases_count": 8,
        "full_scale": "可随项目扩展",
        "est_duration_min": 4,
        "est_tokens": 16000,
        "languages": ["zh"],
        "scenario": "公开 benchmark 完全覆盖不到的空白：同一问题在 dev/prod、不同文档版本、不同轮次下给出互相矛盾的结论，正是「内层说答案对、外层说接口通、谁都不认」的根因之一。",
        "access": "已随仓库预置可跑样本（grader=sandbox，纯本地判分）。",
        "source_kind": "internal",
        "sample_note": "本地构造 8 题，每题给出互相冲突的两个来源，要求输出 canonical_value/source/conflict_detected 后断言其采用当前生效口径并显式标注冲突。非官方原始数据。",
        "recommends_judge": False,
    }),
    # ---------------- 深度档 ----------------
    _curated({
        "id": "humaneval-deep",
        "name": "HumanEval（代码生成·深度子集）",
        "tier": "deep",
        "category": "编码智能体 / 函数级代码生成",
        "object_axes": ["coding_agent"],
        "dimensions": ["coding", "code_generation"],
        "description": "函数级代码生成基准：给定签名与语义要求产出可运行实现，由单元测试判定对错——真正跑起来才算过。",
        "source": "Chen et al. 2021 · arXiv:2107.03374 · openai/openai_humaneval",
        "official_url": "https://huggingface.co/datasets/openai/openai_humaneval",
        "aligned_to": "HumanEval",
        "license": "MIT",
        "commercial_use": True,
        "version": "v1.0 (数据集本身 2021)",
        "updated": "2021-07",
        "data_format": "JSONL (harness Case, grader=sandbox 执行单测)",
        "recommended_grader": "sandbox",
        "suite_file": "humaneval_deep.jsonl",
        "cases_count": 10,
        "full_scale": "164 题（HumanEval）／数百题（HumanEval+、MBPP）",
        "est_duration_min": 8,
        "est_tokens": 30000,
        "languages": ["python"],
        "scenario": "补上「编码能力」这块最大缺口，且无需 Docker：check_code 在受限子进程内 exec 被测实现并跑断言，隔离资源与异常。可商用（MIT）。",
        "access": "已随仓库预置可跑样本（grader=sandbox，纯本地判分、真执行代码）。官方题集需联网主机执行 fetch。",
        "source_kind": "hf_dataset",
        "sample_note": "本地构造 10 题代表性样本（简单到中等难度：字符串/数组/哈希/递归/区间合并/括号匹配等），每题附 2–3 条断言，gold 为参考实现。非官方原始数据。",
        "recommends_judge": False,
    }),
    _curated({
        "id": "ifeval-deep",
        "name": "IFEval（指令跟随·深度子集）",
        "tier": "deep",
        "category": "通用大模型 / 指令跟随",
        "object_axes": ["general_llm"],
        "dimensions": ["instruction_following", "format_control"],
        "description": "可验证指令跟随基准：句数、行长、禁用词、必含词、纯中文、裸 JSON、词数区间、Markdown 表格与末行固定——全部程序化校验。",
        "source": "Zhou et al. 2023 · arXiv:2311.07911 · google/IFEval",
        "official_url": "https://huggingface.co/datasets/google/IFEval",
        "aligned_to": "IFEval",
        "license": "Apache-2.0",
        "commercial_use": True,
        "version": "v1.0 (数据集本身 2023)",
        "updated": "2023-11",
        "data_format": "JSONL (harness Case, grader=sandbox 约束断言)",
        "recommended_grader": "sandbox",
        "suite_file": "ifeval_deep.jsonl",
        "cases_count": 8,
        "full_scale": "约 541 题 / 25 类可验证指令",
        "est_duration_min": 5,
        "est_tokens": 12000,
        "languages": ["zh", "en"],
        "scenario": "交付验收里最高频的争议来源：格式与约束类要求（字数、字段、不得出现某词）非常容易在改写后失效，且完全可以用代码判定，不依赖 judge。可商用（Apache-2.0）。",
        "access": "已随仓库预置可跑样本（grader=sandbox，纯本地判分）。官方题集需联网主机执行 fetch。",
        "source_kind": "hf_dataset",
        "sample_note": "本地构造 8 题代表性样本，约束类型覆盖句数/编号列表/纯中文/裸 JSON/必含词/前缀与禁标点/词数区间/Markdown 表格，gold 逐题满足全部约束并已实测。非官方原始数据。",
        "recommends_judge": False,
    }),
    _curated({
        "id": "fineval-deep",
        "name": "FinEval（中文金融·深度子集）",
        "tier": "deep",
        "category": "垂直行业智能体 / 金融",
        "object_axes": ["vertical_finance"],
        "dimensions": ["domain_knowledge", "single_turn_qa"],
        "description": "中文金融领域基准：证券基础、估值、利率体系、资产配置、货币政策、固定收益、基金治理、信息披露共 10 类实务口径。",
        "source": "Zhang et al. 2023 · arXiv:2308.09975 · SUFE-AIFLM-Lab/FinEval",
        "official_url": "https://huggingface.co/datasets/SUFE-AIFLM-Lab/FinEval",
        "aligned_to": "FinEval",
        "license": "CC-BY-NC-4.0（非商用）",
        "commercial_use": False,
        "version": "v1.0 (数据集本身 2023)",
        "updated": "2023-08",
        "data_format": "JSONL (harness Case, MCQ)",
        "recommended_grader": "code(exact/contains)",
        "suite_file": "fineval_deep.jsonl",
        "cases_count": 10,
        "full_scale": "约 4,600 题 / 34 学科（金融学术与执业）",
        "est_duration_min": 4,
        "est_tokens": 12000,
        "languages": ["zh"],
        "scenario": "金融行业客户问「你有没有我们行业的用例」时的正面回答；业务正确性（而非通用能力）口径。注意许可能为非商用，商用前需法务确认。",
        "access": "已随仓库预置可跑样本；官方抽样需联网主机执行 fetch。许可 CC-BY-NC 类，商用前须法务确认。",
        "source_kind": "hf_dataset",
        "sample_note": "本地构造 10 题代表性样本（A 股涨跌幅、PE 计算、LPR、分散投资、存款准备金率、债券价格与利率、基金管理人职责、权益类资产、复利计算、定期报告范围），答案已逐题核对。非官方原始数据。",
        "recommends_judge": False,
    }),
    _curated({
        "id": "cmeval-deep",
        "name": "CMExam（中文医疗·深度子集）",
        "tier": "deep",
        "category": "垂直行业智能体 / 医疗",
        "object_axes": ["vertical_medical"],
        "dimensions": ["domain_knowledge", "single_turn_qa"],
        "description": "中文医疗领域基准：基础生命体征、急救、公共卫生、心血管、内分泌、药事管理、输血医学、合理用药、营养评估共 10 类。",
        "source": "Liu et al. 2024 · arXiv:2306.15033 · CMExam",
        "official_url": "https://github.com/williamliujl/CMExam",
        "aligned_to": "CMExam · MedQA",
        "license": "见官方仓库（商用前需确认）",
        "commercial_use": False,
        "version": "v1.0 (数据集本身 2023)",
        "updated": "2023-06",
        "data_format": "JSONL (harness Case, MCQ)",
        "recommended_grader": "code(exact/contains)",
        "suite_file": "cmeval_deep.jsonl",
        "cases_count": 10,
        "full_scale": "约 68,000 题（国家医师资格考试风格）",
        "est_duration_min": 4,
        "est_tokens": 12000,
        "languages": ["zh"],
        "scenario": "医疗行业 Agent 的业务正确性基线；同时是「医疗建议越界」的红线素材来源（见 safetybench-advanced 的 SB-09）。",
        "access": "已随仓库预置可跑样本；官方抽样需联网主机执行 fetch。许可待确认。",
        "source_kind": "hf_dataset",
        "sample_note": "本地构造 10 题代表性样本（心率/体温/CPR 频率/传染病三环节/高血压与糖尿病诊断切点/处方药管理/献血量/抗生素使用/BMI），均取公认临床常识口径，已逐题核对。非官方原始数据。",
        "recommends_judge": False,
    }),
    _curated({
        "id": "longcontext-deep",
        "name": "长上下文定位（自研·深度）",
        "tier": "deep",
        "category": "智化融合系统 / 长上下文·关键信息定位",
        "object_axes": ["general_llm"],
        "dimensions": ["long_context", "information_retrieval"],
        "description": "海量文档里的关键信息定位：在制度、手册、纪要、合同、日志、政策、方案、财报八类长文本中，跨段定位唯一正确答案，并抵抗同构干扰项。",
        "source": "本项目自研（对齐 LongBench / Needle-in-a-Haystack 思路）",
        "official_url": "https://github.com/THUDM/LongBench",
        "aligned_to": "LongBench · Needle-in-a-Haystack",
        "license": "内部自研",
        "commercial_use": True,
        "version": "v1.0",
        "updated": "2026-09",
        "data_format": "JSONL (harness Case, grader=code 数值/日期精确匹配)",
        "recommended_grader": "code(exact/contains)",
        "suite_file": "longcontext_deep.jsonl",
        "cases_count": 8,
        "full_scale": "可随项目扩展",
        "est_duration_min": 6,
        "est_tokens": 30000,
        "languages": ["zh"],
        "scenario": "合同与制度类 Agent 的高频翻车点：长文档里同类数字/日期/比例互相干扰（如卖方 0.5% 与买方 0.3%、首批与第二批发布日），要求精确定位而非近似。",
        "access": "已随仓库预置可跑样本（grader=code，确定性判分）。",
        "source_kind": "internal",
        "sample_note": "本地构造 8 题，每题含 700–1100 字长上下文，meta 标注 needle / distractors / context_span，gold 为唯一数值或日期。非官方原始数据。",
        "recommends_judge": False,
    }),
    _curated({
        "id": "multiagent-handoff-deep",
        "name": "多智能体交接失真（自研·深度）",
        "tier": "deep",
        "category": "多智能体协作 / 交接契约与责任归属",
        "object_axes": ["multi_agent"],
        "dimensions": ["multi_agent", "handoff", "trajectory"],
        "description": "多智能体系统的交接契约验收：任务分解、委派、上下文传递、并行冲突、一票否决短路、留痕归档。判分看轨迹覆盖率与首错步骤定位。",
        "source": "本项目自研（对齐 MultiAgentBench/MARBLE 与轨迹级归因思路）",
        "official_url": "https://github.com/ulab-uiuc/MARBLE",
        "aligned_to": "MultiAgentBench · MARBLE",
        "license": "内部自研",
        "commercial_use": True,
        "version": "v1.0",
        "updated": "2026-09",
        "data_format": "JSONL (harness Case, grader=trajectory)",
        "recommended_grader": "trajectory",
        "suite_file": "multiagent_handoff_deep.jsonl",
        "cases_count": 8,
        "full_scale": "可随项目扩展",
        "est_duration_min": 6,
        "est_tokens": 24000,
        "languages": ["zh"],
        "scenario": "多智能体把「交界层」从 1 类（模型↔工具）扩成 N 类（agent↔agent），并新增分解错/委派错/上下文丢失/结果冲突/死循环/责任真空/成本爆炸等单智能体没有的失效模式。本集用 trajectory 评分器给出交接覆盖率与最早出错步骤，使失败可归因而非只看终分。",
        "access": "已随仓库预置可跑样本（grader=trajectory，确定性判分，无需 judge 模型）。",
        "source_kind": "internal",
        "sample_note": "本地构造 8 题，覆盖招投标评审委员会／虚拟研发团队／智能投研／内容工作室／能源运营／红蓝对抗／客服升级链／跨部门审批八个多智能体场景；meta.expected_steps 为交接清单，gold 为逐步轨迹。非官方原始数据。",
        "recommends_judge": False,
    }),
    # ---------------- 专家档（环境类，仅元数据登记） ----------------
    {
        "id": "swebench-verified",
        "name": "SWE-bench Verified（代码·专家/环境）",
        "tier": "expert",
        "category": "编码智能体 / 真实仓库修复（人工校验子集）",
        "object_axes": ["coding_agent"],
        "dimensions": ["coding", "tool_use", "environment"],
        "description": "SWE-bench 的人工校验子集（500 题），剔除描述不清或无解的样本，是目前编码 Agent 最被认可的端到端口径。",
        "source": "Jimenez et al. 2024 · arXiv:2310.06770 · princeton-nlp/SWE-bench_Verified",
        "official_url": "https://huggingface.co/datasets/princeton-nlp/SWE-bench_Verified",
        "license": "MIT",
        "commercial_use": True,
        "version": "Verified (500 题)",
        "updated": "2024-08",
        "data_format": "需代码沙箱（Docker）执行，非纯 JSONL",
        "recommended_grader": "sandbox",
        "suite_file": None,
        "cases_count": 500,
        "full_scale": "500 题（Verified）／2,294 题（Full）",
        "est_duration_min": 180,
        "est_tokens": 800000,
        "languages": ["python"],
        "scenario": "编码 Agent 的对外可比口径：客户若用 SWE-bench 数字对标，我们至少要能解释与 SWE-bench Verified 的关系。需 Docker 沙箱跑测试，属重活，仅元数据占位。",
        "access": "Phase 2/3 接入代码沙箱桥接；当前仅目录登记。接入：pip install swebench + 拉取对应仓库镜像。",
        "requires_env": True,
        "env_notes": "每题需检出对应仓库与提交、应用补丁、运行仓库自身测试；单题分钟级、镜像体积大。",
        "source_kind": "hf_dataset",
        "recommends_judge": False,
    },
    {
        "id": "tau2-bench",
        "name": "τ²-bench（多轮工具调用·专家/环境）",
        "tier": "expert",
        "category": "特定用途智能体 / 工具调用（多轮·双控制）",
        "object_axes": ["tool_use_agent"],
        "dimensions": ["multi_turn", "tool_use", "multi_agent", "environment"],
        "description": "τ-bench 的继任者：双向控制（agent 与用户都能操作同一真实环境），测多轮策略遵循与状态一致性。",
        "source": "Yao et al. 2024–2025 · sierra-research/tau2-bench",
        "official_url": "https://github.com/sierra-research/tau2-bench",
        "license": "MIT",
        "commercial_use": True,
        "version": "v2 (2025)",
        "updated": "2025",
        "data_format": "需沙箱 + 模拟用户 + 领域 API（电信/零售/航空）",
        "recommended_grader": "sandbox",
        "suite_file": None,
        "cases_count": 300,
        "full_scale": "数百任务（电信/零售/航空三域）",
        "est_duration_min": 180,
        "est_tokens": 700000,
        "languages": ["en"],
        "scenario": "多轮工具调用的最贴近生产口径：策略文档 + 状态一致性 + 用户模拟。需沙箱与领域 API 桩，属重活，仅元数据占位。",
        "access": "Phase 2/3 接入沙箱桥接；当前仅目录登记。",
        "requires_env": True,
        "env_notes": "需沙箱、模拟用户与领域 API 桩；多轮、耗时长。",
        "source_kind": "git",
        "recommends_judge": False,
    },
    {
        "id": "terminal-bench",
        "name": "Terminal-Bench（终端操作·专家/环境）",
        "tier": "expert",
        "category": "编码智能体 / 终端与系统工程操作",
        "object_axes": ["coding_agent", "general_assistant"],
        "dimensions": ["tool_use", "environment", "multi_step"],
        "description": "在真实终端里完成系统与工程任务（编译、调试、文件处理、服务排障），任务级判定而非函数级。",
        "source": "Stanford / Laude Institute 2025 · laude-institute/terminal-bench",
        "official_url": "https://github.com/laude-institute/terminal-bench",
        "license": "Apache-2.0",
        "commercial_use": True,
        "version": "v1.x (2025)",
        "updated": "2025",
        "data_format": "需容器化终端环境 + 任务级校验",
        "recommended_grader": "sandbox",
        "suite_file": None,
        "cases_count": 100,
        "full_scale": "约 100+ 任务",
        "est_duration_min": 120,
        "est_tokens": 500000,
        "languages": ["en"],
        "scenario": "运维/DevOps 类 Agent 的验收口径；与 SWE-bench（改代码）互补，看的是「能不能把环境搞对」。需容器，属重活，仅元数据占位。",
        "access": "Phase 3 接入容器化终端桥接；当前仅目录登记。",
        "requires_env": True,
        "env_notes": "需容器镜像与任务级校验脚本；单任务分钟级。",
        "source_kind": "git",
        "recommends_judge": False,
    },
    {
        "id": "multiagentbench",
        "name": "MultiAgentBench / MARBLE（多智能体·专家/环境）",
        "tier": "expert",
        "category": "多智能体协作 / 多环境协作与竞争",
        "object_axes": ["multi_agent"],
        "dimensions": ["multi_agent", "collaboration", "environment"],
        "description": "在多种环境下评测多智能体协作与竞争，指标含任务完成度与协作质量（里程碑达成、通信结构），是「交接失真」的公开对照口径。",
        "source": "Zhu et al. 2025 · MARBLE · arXiv:2503.01935",
        "official_url": "https://github.com/ulab-uiuc/MARBLE",
        "license": "MIT",
        "commercial_use": True,
        "version": "v1.0 (2025)",
        "updated": "2025-03",
        "data_format": "需多环境（研究/编码/数据库/游戏）+ 多智能体编排",
        "recommended_grader": "sandbox",
        "suite_file": None,
        "cases_count": 6,
        "full_scale": "6 类协作场景 × 多环境",
        "est_duration_min": 240,
        "est_tokens": 900000,
        "languages": ["en"],
        "scenario": "多智能体方向的公开对照：我们自研的 multiagent-handoff-deep 与之互补——它是任务口径，我们补的是「交接契约与首错归因」。环境重，仅元数据占位。",
        "access": "Phase 3 接入多智能体编排桥接；当前仅目录登记。",
        "requires_env": True,
        "env_notes": "需多环境栈 + 多智能体编排框架；资源最重的一类。",
        "source_kind": "git",
        "recommends_judge": False,
    },
]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true", help="只打印将要发生的变更，不写文件")
    args = ap.parse_args()

    with open(CATALOG, encoding="utf-8") as f:
        cat = json.load(f)

    existing = {d["id"]: i for i, d in enumerate(cat["datasets"])}
    added, updated = [], []
    for e in NEW:
        if e["id"] in existing:
            cat["datasets"][existing[e["id"]]] = e
            updated.append(e["id"])
        else:
            cat["datasets"].append(e)
            added.append(e["id"])

    cat["datasets"].sort(key=lambda d: (TIER_ORDER.index(d.get("tier", "expert")), d["id"]))
    cat["generated_by"] = ("Phase 2 · 数据集扩容：基础/进阶/深度三档补齐 + 行业垂直 + "
                           "集成风险面与多智能体自研集")

    tiers: dict[str, int] = {}
    for d in cat["datasets"]:
        tiers[d.get("tier", "other")] = tiers.get(d.get("tier", "other"), 0) + 1

    print(f"catalog: {CATALOG}")
    print(f"  total={len(cat['datasets'])}  tiers={tiers}")
    print(f"  added({len(added)}): {', '.join(added) or '-'}")
    print(f"  updated({len(updated)}): {', '.join(updated) or '-'}")

    runnable = sum(1 for d in cat["datasets"] if d.get("suite_file") and not d.get("requires_env"))
    env = sum(1 for d in cat["datasets"] if d.get("requires_env"))
    print(f"  runnable(suite_file)={runnable}  env(requires_env)={env}")

    if args.dry_run:
        print("  [dry-run] 未写入")
        return 0

    with open(CATALOG, "w", encoding="utf-8") as f:
        json.dump(cat, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print("  written.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
